-- Active: 1735319124226@@mysql-1fcc4b03-cristian-4d9d.l.aivencloud.com@18115@CARVIA
-- Active: 1732127790281@@mysql-1fcc4b03-cristian-4d9d.l.aivencloud.com@18115@information_schema
CREATE DATABASE IF NOT EXISTS CARVIA;
USE CARVIA;


CREATE TABLE Anuncios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    fecha DATE NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    precio DOUBLE NOT NULL,
    urlFoto VARCHAR(2083) NOT NULL
);
CREATE TABLE IF NOT EXISTS Users (
	idUs INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    full_name VARCHAR(255),
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    address VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS Vehicles (
    idVe INT PRIMARY KEY AUTO_INCREMENT,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    year INT NOT NULL,
    kilometers INT NOT NULL, 
    fuel_type VARCHAR(50) NOT NULL,
    transmission VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Advertisements (
    idAd INT PRIMARY KEY AUTO_INCREMENT,
    idVe INT NOT NULL REFERENCES Vehicles(idVe) ON DELETE CASCADE,
    idUs INT NOT NULL REFERENCES Users(idUs) ON DELETE CASCADE,
    date DATE NOT NULL,
    description TEXT,
    price DOUBLE NOT NULL,
    images VARCHAR(2083) 
);

CREATE TABLE IF NOT EXISTS Payments (
    idPay INT PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(50) NOT NULL,
    amount DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS Shopping (
    idShop INT PRIMARY KEY AUTO_INCREMENT,
    idVe INT NOT NULL REFERENCES Vehicles(idVe) ON DELETE CASCADE,
    idPay INT NOT NULL REFERENCES Payments(idPay) ON DELETE CASCADE,
    idUs INT NOT NULL REFERENCES Users(idUs) ON DELETE CASCADE,
    date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Account(
    idAc INT PRIMARY KEY AUTO_INCREMENT,
    idUs INT NOT NULL REFERENCES Users(idUs) ON DELETE CASCADE,
    state VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Messages (
    idMes INT PRIMARY KEY AUTO_INCREMENT,
    idUs INT NOT NULL REFERENCES Users(idUs) ON DELETE CASCADE,
    text TEXT NOT NULL,
    date DATE NOT NULL
);



